label = "English"
weight = 2
title = "Happy Backending"
copyright = "Happy Backending"

[params]
  [params.author]
    name = "Happy Backending"
    image = "img/logo.jpg"
    headline = "Backend development, but happy"
    links = [
      { youtube = "https://www.youtube.com/channel/UC0AYdNU4NtuxWASP4Qlil7w" },
      { telegram = "https://t.me/happybackending_feed" },
      { github = "https://github.com/halon176" },
      { email = "mailto:happybackending@gmail.com" },
      { link = "https://halon.cc" }
    ]
